sudo: required
language: php
php: 7.1

services:
  - mysql
  - docker
  - postgresql

matrix:
  include:
    - php: 7.1
      env:
        - DB=mysql
        - SELENIUM=1
        - COVERAGE=1
    - php: 7.0
      env:
        - DB=mysql
        - SELENIUM=1
    - php: 7.2
      env:
        - DB=mysql
        - SELENIUM=1
    - php: 7.1
      env: DB=postgres
  allow_failures:
    - env: DB=postgres
  fast_finish: true

# Run pushed branches build on master and tagged version
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

addons:
  postgresql: "9.6"
  chrome: stable

before_install:
  - mkdir -p $TRAVIS_BUILD_DIR/results/coverage
  - cp scripts/tests/.env.$DB.travis .env
  - if [[ "$DB" == "mysql" ]]; then mysql -v -e 'CREATE DATABASE monica;'; fi
  - if [[ "$DB" == "postgres" ]]; then psql -e -c 'CREATE DATABASE monica;' -U postgres; fi
  - composer self-update

install:
  # Get packages
  - travis_retry composer install --no-interaction --no-suggest --ignore-platform-reqs

  # Build js and css assets
  - php artisan vue-i18n:generate
  - npm install
  - npm run production

before_script:
  - php artisan migrate --env=testing --no-interaction -vvv
  - php artisan db:seed --env=testing --no-interaction -vvv

  # Start Xvfb
  - "export DISPLAY=:99.0"
  - if [[ "$SELENIUM" == "1" && "$SAUCELABS" != "1" ]]; then /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16; fi

  # Start chromedriver
  - bash -c "if [[ \"$SELENIUM\" == \"1\" && \"$SAUCELABS\" != \"1\" ]]; then ./vendor/bin/chromedriver; fi" &
  
script:
  # Run unit tests
  - vendor/bin/phpunit -c phpunit${DB/mysql/}.xml

  # Start http server
  - bash -c "if [[ \"$SELENIUM\" == \"1\" ]]; then php -S localhost:8000 -t $TRAVIS_BUILD_DIR/public $TRAVIS_BUILD_DIR/scripts/tests/server-cc.php 2>/dev/null; fi" &
  - if [[ "$SELENIUM" == "1" ]]; then until $(nc -z localhost 8000); do sleep 1; echo Waiting for http server to start...; done; fi

  # Run browser tests
  - if [[ "$SELENIUM" == "1" ]]; then php artisan dusk; fi

after_script:
  - if [[ "$SELENIUM" == "1" ]]; then scripts/tests/travis-report.sh 2>/dev/null; fi
  - if [[ "$COVERAGE" == "1" ]]; then vendor/bin/phpcov merge --clover=$TRAVIS_BUILD_DIR/results/coverage2.xml $TRAVIS_BUILD_DIR/results/coverage/; fi
  - if [[ "$COVERAGE" == "1" ]]; then bash <(curl -s https://codecov.io/bash); fi
  - if [[ "$COVERAGE" == "1" ]]; then scripts/tests/travis-sonar.sh; fi

cache:
  directories:
    - $HOME/.composer/cache/files
    - node_modules
    - $HOME/.sonar/cache
    - $HOME/sonarscanner
    - $HOME/sonarlauncher

jobs:
  include:
    - stage: Tests
      php: 7.1
      env:
        - DB=mysql
        - SELENIUM=1
        - COVERAGE=1

    - stage: Tests
      php: 7.0
      env:
        - DB=mysql
        - SELENIUM=1

    - stage: Tests
      php: 7.2
      env:
        - DB=mysql
        - SELENIUM=1

    - stage: Tests
      allow_failure: true 
      php: 7.1
      env: DB=postgres

    - stage: Deploy
      if: tag IS present
      skip_cleanup: true
      before_install:
        - cp scripts/tests/.env.mysql.travis .env
        - composer self-update

      install:
        # Get packages without require-dev
        - travis_retry composer install --no-interaction --no-suggest --ignore-platform-reqs --no-dev
        # Build js and css assets
        - php artisan vue-i18n:generate
        - npm install
        - npm run production

      before_script: skip

      script:
        - make dist

      after_script: skip

      before_deploy:
        - make .travis.deploy.json

      deploy:
        provider: bintray
        file: .travis.deploy.json
        skip_cleanup: true
        user: $BINTRAY_USER
        key: $BINTRAY_APIKEY
        on:
          all_branches: true

    - stage: Deploy
      if: tag IS present
      before_install:
        - cp scripts/tests/.env.mysql.travis .env
        - docker-compose --version

      install: skip
      before_script: skip

      script:
        - make docker_build
        - echo $BINTRAY_APIKEY | docker login -u $BINTRAY_USER --password-stdin monicahq-docker-docker.bintray.io
        - make docker_push_bintray

      after_script: skip

    - stage: Deploy
      if: tag IS present
      before_install:
        - scripts/vagrant/install-vagrant.sh

      install: skip
      before_script: skip

      script:
        - make vagrant_build
      after_script: skip

      before_deploy:
        - DEPLOY_TEMPLATE=scripts/vagrant/build/.travis.deploy.json.in make .travis.deploy.json
      deploy:
        provider: bintray
        file: .travis.deploy.json
        skip_cleanup: true
        user: $BINTRAY_USER
        key: $BINTRAY_APIKEY
        on:
          all_branches: true
