sudo: required
language: php

php:
  - 7.1

services:
  - mysql

jdk:
  - oraclejdk8

addons:
  chrome: stable
#  sauce_connect:
#    username: "asbiin"
#  jwt:
#    secure: "niuYhwCsFVUHS6DU3j0xi24habQOSqKpzo7qUlGmlx1x31wZNDrl+wfifeTVv6nnjoShyr4s6svn3ULl1K8tQMdyHJlO247WKMg/PSnaSUyll5+luuP5SLpV+USP8g9a7HAjU+jQO5uE/GXKDDQcD+o5dV6gv9stmc9u/np45kwgVx55bj013ll0M5qlyflJZFgp3b/M+bvqkvIFDPN2U7iFs0dkhqxBI+6qbTAN4aTtxPSPrsYdt9W8Re1suzy2/CJEEQ2xKE4zm7WQ2dg6BrpbaU2bdG6wWZUw2toA8iCyxFgbJUlXmAjPEQ5Wr+gWEQ9bLcwCIoHxUMIRbqY/SNzve7KnGXOUEF0yttyAv3aq9STA58Mr+H15zXdA5ZAwpE/tNojfaacEya/bg9fwUWOCqrPXIhwFirhf8oD2y8n+SWD27rP0qD9um9HGqGkh6bqFefIZi2xVzLya1r/2kxqFskrj+0xPjjKYwMwJIM5s7HyrtIxR7QTpFEbgHpZjCmT31I65ds56ec34wbZ0W61bm4aQAxz7UIedCYsTrqtTzTYxUJEht3/1D5FH0PSBWQACJmdjSHvh0pP7zzG2cqzq2IhHCSZjnhh6LGUPQtgZh3kq1fSP0Zw74iSVrxQETsGoPwYA6R38e+V39vV8yUHjMUXNPIhgcQQZHiZcEWI="

env:
  global:
#    - SAUCELABS=1

before_script:
  - cp .env.travis .env
  - mkdir -p results/coverage
  - mysql -e 'create database monica;'
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

  - |
    if [ ! "$SAUCELABS" = "1" ]; then
      # Start Xvfb
      export DISPLAY=:99.0
      /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24

      # Start selenium server
      java -jar $(pwd)/vendor/se/selenium-server-standalone/bin/selenium-server-standalone.jar -role hub -log selenium-server.log &
      until $(nc localhost -z 4444); do sleep 1; echo Waiting for selenium hub to start...; done

      # Start selenium node for headless Chrome
      java -Dwebdriver.chrome.driver="$(pwd)/vendor/bin/chromedriver" -jar $(pwd)/vendor/se/selenium-server-standalone/bin/selenium-server-standalone.jar -role node -port 8910 -log selenium-node.log &
      until $(nc localhost -z 8910); do sleep 1; echo Waiting for selenium node to start...; done
    fi

script:
  - php artisan migrate --env=testing --no-interaction -vvv
  - php artisan db:seed --env=testing --no-interaction -vvv
  
  # Run unit tests
  - vendor/bin/phpunit

  # Start http server
  - php -S 127.0.0.1:8000 -t public server-cc.php &
  - until $(nc -z localhost 8000); do sleep 1; echo Waiting for laravel server to start...; done;

  # Run browser tests
  - if [ "$SAUCELABS" = "1" ]; then vendor/bin/steward run travis chrome -vvv --server-url=http://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@localhost:4445 --capability="tunnel-identifier:'${TRAVIS_JOB_NUMBER}'"; fi
  - if [ ! "$SAUCELABS" = "1" ]; then vendor/bin/steward run travis chrome -vvv; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_script:
  - vendor/bin/steward results -vvv
  - .ci/travis-report.sh 2>/dev/null
  - cat selenium-server.log
  - cat selenium-node.log
  - vendor/bin/phpcov merge --clover=$(pwd)/results/coverage2.xml $(pwd)/results/coverage
  - ./travis-sonar.sh

cache:
  directories:
    - $HOME/.sonar/cache
    - $HOME/sonarscanner
    - $HOME/sonarlauncher
