version: '3'
services:
  monicahq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    links:
      - mysql
      - couchdb
    ports:
      - 8080:80
    env_file: .env.dev
    environment:
      - PASSWORD_CLIENT_ID=10
      - PASSWORD_CLIENT_SECRET=4eYqKmvMr1nLhRNiI30fkPARM77j90MgBTaJADgN
    volumes:
      - ./storage:/var/www/monica/storage
      - ./app:/var/www/monica/app
      - ./config:/var/www/monica/config
      - ./routes:/var/www/monica/routes
      - ./database:/var/www/monica/database
      - ./resources:/var/www/monica/resources
      - ./public:/var/www/monica/public

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=sekret_root_password
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    volumes:
      - /var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: sekret_root_password
    restart: always
    ports:
      - "3000:80"
    volumes:
      - "/sessions"
  
  couchdb:
    image: couchdb:2.1
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
