# CircleCI build for https://circleci.com/gh/monicahq/monica
# Largely adapted, with the help of https://github.com/angular/angular/blob/master/.circleci/config.yml

version: 2

# Note: YAML anchors allow an object to be re-used, reducing duplication.
# The ampersand declares an alias for an object, then later the `<<: *name`
# syntax dereferences it.
# See http://blog.daemonl.com/2016/02/yaml.html
# To validate changes, use an online parser, eg.
# http://yaml-online-parser.appspot.com/

aliases:
# Some variables
  - &composer_key_base composer-v3-
  - &composer_key composer-v3-{{ checksum "composer.lock" }}
  - &node_key_base node-v4-
  - &node_key node-v4-{{ checksum "package.json" }}
  - &assets_key assets-v2-{{ .Revision }}
  - &sonar_key_base sonarscanner-v2-
  - &sonar_key sonarscanner-v2-{{ .Environment.SONAR_VERSION }}-{{ checksum "scripts/tests/runsonar.sh" }}
  - &root ~/monica

# Defaults env
  - &defaults
    working_directory: *root

# After checkout, rebase on top of master.
# Similar to travis behavior, but not quite the same.
# See https://discuss.circleci.com/t/1662
  - &post_checkout
    post: git pull --ff-only origin "refs/pull/${CIRCLE_PULL_REQUEST//*pull\//}/merge"

  - &prepare-environment
    run:
      name: Prepare environment
      command: |
        mkdir -p results/coverage
        cp scripts/tests/.env.mysql .env
        touch .sentry-release
  - &yarn-install
    run:
      name: yarn install
      command: yarn inst
  - &prepare-db
    run:
      name: Prepare database
      command: |
        dockerize -wait tcp://127.0.0.1:3306 -timeout 60s
        mysql --protocol=tcp -u root -e "CREATE DATABASE IF NOT EXISTS monica CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
        php artisan migrate --no-interaction -vvv
  - &seed-test-db
    run:
      name: Seed database
      command: |
        php artisan db:seed --no-interaction -vvv
        php artisan passport:keys --no-interaction -vvv
  - &http-server-cc
    run:
      name: Run http server
      command: php -S localhost:8000 -t public scripts/tests/server-cc.php
      background: true
  - &http-server
    run:
      name: Run http server
      command: php artisan serve
      background: true
  - &wait-for-server
    run:
      name: Wait for http server
      command: dockerize -wait tcp://localhost:8000 -timeout 60s
  - &unit-tests
    run:
      name: Run unit tests
      command: |
        php artisan route:cache
        TESTSUITE=$(echo -e "Api-and-Feature\nUnit" | circleci tests split)
        phpdbg -dmemory_limit=4G -qrr vendor/bin/phpunit -c phpunit.xml --log-junit ./results/junit/unit/results${CIRCLE_NODE_INDEX}.xml --coverage-clover ./results/coverage${CIRCLE_NODE_INDEX}.xml --testsuite $TESTSUITE
  - &psalm
    run:
      name: Run psalm
      command: vendor/bin/psalm --show-info=false
  - &phpstan
    run:
      name: Run phpstan
      command: php artisan code:analyse
  - &browser-tests
    run:
      name: Run browser tests
      command: php artisan dusk --log-junit results/junit/dusk/results3.xml
  - &browser-cypress
    run:
      name: Run browser tests (cypress)
      command: |
        mysqldump -u root -h 127.0.0.1 -P 3306 monica > monicadump.sql
        $(yarn bin)/cypress run --config "baseUrl=http://localhost:8000" --record --reporter mocha-multi-reporters --reporter-options configFile=.circleci/cypressmocha.json
  - &fix-coverage
    run:
      name: Fix coverage
      command: |
        vendor/bin/phpcov merge --clover=results/coverage3.xml results/coverage/
        rm -rf results/coverage
  - &fix-coverage2
    run:
      name: Fix coverage
      command: |
        vendor/bin/phpcov merge --clover=results/coverage4.xml results/coverage/
        rm -rf results/coverage
  - &selenium
    run:
      name: Run selenium chromedriver
      command: vendor/bin/chromedriver
      background: true
  - &remove-xdebug
    run:
      name: Remove xdebug
      command: |
        sudo rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  - &docker-install
    run:
      name: Install docker_squash
      command: |
        sudo apt-get update
        sudo apt-get install -y python-pip
        pip install docker-squash "docker < 3"
  - &docker-build
    run:
      name: Make docker image
      command: |
        docker-compose --version
        make docker_build
        make docker_squash
  - &docker-push-bintray
    run:
      name: Publish docker image
      command: |
        echo $BINTRAY_APIKEY | docker login -u $BINTRAY_USER --password-stdin monicahq-docker-docker.bintray.io
        make docker_push_bintray


  - &restore_composer
    restore_cache:
      keys:
        - *composer_key
        - *composer_key_base
  - &restore_node
    restore_cache:
      keys:
        - *node_key
        - *node_key_base


jobs:
  build:
    <<: *defaults
    docker:
      - image: monicahq/circleci-docker-centralperk:latest

    steps:
      - checkout:
          <<: *post_checkout
      - *prepare-environment

      - run:
          name: Prepare environment
          command: |
            sudo composer self-update
            yarn global add greenkeeper-lockfile@1

      ## COMPOSER
      - *restore_composer
      - run: composer install --no-interaction --no-suggest --ignore-platform-reqs
      - save_cache:
          key: *composer_key
          paths: ~/.composer/cache/
      - persist_to_workspace:
          root: *root
          paths: vendor

      ## NODE.JS
      - *restore_node
      - run:
          name: Update yarn lockfile
          command: CIRCLE_PREVIOUS_BUILD_NUM=$(test "$CIRCLE_BRANCH" != "master" -a "greenkeeper[bot]" = "`git log --format="%an" -n 1`" || echo false) CI_PULL_REQUEST="" GK_LOCK_YARN_OPTS="--ignore-engines" $(yarn global bin)/greenkeeper-lockfile-update
      - *yarn-install
      - save_cache:
          key: *node_key
          paths: ~/.cache
      - run:
          name: Upload yarn lockfile
          command: |
            CIRCLE_PREVIOUS_BUILD_NUM=$(test "$CIRCLE_BRANCH" != "master" -a "greenkeeperio-bot" = "`git log --format="%an" -n 1`" || echo false) $(yarn global bin)/greenkeeper-lockfile-upload
            cat gk-lockfile-git-push.err || true
            rm -f gk-lockfile-git-push.err || true

      # Update js and css assets eventually
      - run:
          name: Check js and vue lint
          command: yarn lint
      - run:
          name: Update assets
          command: scripts/ci/update-assets.sh

  tests-7.2:
    <<: *defaults
    docker:
      - image: monicahq/circleci-docker-centralperk:latest
      - image: circleci/mysql:5.7-ram
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
    parallelism: 2

    steps:
      - checkout:
          <<: *post_checkout
      - attach_workspace:
          at: *root
      - *prepare-environment
      - *remove-xdebug
      - *prepare-db
      - *seed-test-db
      - *unit-tests
      - store_test_results:
          path: results/junit
      - store_artifacts:
          path: results/junit
      - persist_to_workspace:
          root: *root
          paths: results

  psalm:
    <<: *defaults
    docker:
      - image: monicahq/circleci-docker-centralperk:latest

    steps:
      - checkout:
          <<: *post_checkout
      - attach_workspace:
          at: *root
      - *prepare-environment
      - *psalm

  phpstan:
    <<: *defaults
    docker:
      - image: monicahq/circleci-docker-centralperk:latest

    steps:
      - checkout:
          <<: *post_checkout
      - attach_workspace:
          at: *root
      - *prepare-environment
      - *phpstan

  tests-browser-7.2:
    <<: *defaults
    docker:
      - image: monicahq/circleci-docker-centralperk:latest
      - image: circleci/mysql:5.7-ram
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''

    steps:
      - checkout:
          <<: *post_checkout
      - attach_workspace:
          at: *root
      - *prepare-environment
      - *prepare-db
      - *seed-test-db
      - *selenium
      - *http-server-cc
      - *wait-for-server
      - *browser-tests
      - *fix-coverage
      - store_test_results:
          path: results/junit
      - store_artifacts:
          path: results/junit
      - store_artifacts:
          path: tests/Browser/screenshots
      - persist_to_workspace:
          root: *root
          paths: results

  tests-e2e:
    <<: *defaults
    docker:
      - image: monicahq/circleci-docker-centralperk:latest
      - image: circleci/mysql:5.7-ram
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''

    steps:
      - checkout:
          <<: *post_checkout
      - attach_workspace:
          at: *root
      - *prepare-environment
      - *restore_node
      - *yarn-install
      - *prepare-db
      - *http-server-cc
      - *wait-for-server
      - *browser-cypress
      - *fix-coverage2
      - store_test_results:
          path: results/junit
      - store_artifacts:
          path: results/junit
      - store_artifacts:
          path: tests/cypress/screenshots
      - persist_to_workspace:
          root: *root
          paths: results

  reporting:
    <<: *defaults
    docker:
      - image: circleci/php:7.2-node

    steps:
      - checkout:
          <<: *post_checkout
      - attach_workspace:
          at: *root
      - *prepare-environment
      - restore_cache:
          keys:
            - *sonar_key
            - *sonar_key_base

      - run:
          name: Merge junit files
          command: |
            yarn global add junit-merge
            $(yarn global bin)/junit-merge --recursive --dir results/junit --out results/results.xml
      - run:
          name: Run sonar scanner
          command: |
            export SONAR_RESULT=./results/results.xml
            export SONAR_COVERAGE=$(ls -m ./results/coverage*.xml | sed 's/ //g' | sed ':a;N;$!ba;s/\n//g')
            scripts/tests/runsonar.sh

      - save_cache:
          key: *sonar_key
          paths:
            - ~/sonarscanner
            - ~/.sonar/cache

  deploy-assets:
    <<: *defaults
    docker:
      - image: circleci/php:7.2

    steps:
      - checkout:
          <<: *post_checkout
      - attach_workspace:
          at: *root

      - run: make assets
      - run: make push_bintray_assets

  deploy-dist:
    <<: *defaults
    docker:
      - image: circleci/php:7.2

    steps:
      - checkout:
          <<: *post_checkout
      - attach_workspace:
          at: *root
      - run: composer install --no-interaction --no-suggest --ignore-platform-reqs --no-dev
      - run: make dist
      - run: make push_bintray_dist

  deploy-docker-master:
    <<: *defaults
    machine: true

    steps:
      - checkout:
          <<: *post_checkout
      - attach_workspace:
          at: *root
      - *prepare-environment
      - *docker-install
      - *docker-build
      - *docker-push-bintray

  deploy-docker-staging:
    <<: *defaults
    machine: true

    steps:
      - run:
          name: Update staging
          command: |
            ssh $SSH_USER@$SSH_HOST "docker-compose -f $DOCKER_FILE pull"
            ssh $SSH_USER@$SSH_HOST "docker-compose -f $DOCKER_FILE up -d"

  deploy-docker:
    <<: *defaults
    machine: true

    steps:
      - checkout:
          <<: *post_checkout
      - attach_workspace:
          at: *root
      - *prepare-environment
      - *docker-install
      - *docker-build
      - *docker-push-bintray
      - run:
          name: Publish docker image
          command: |
            echo $DOCKER_LOGIN | docker login -u $DOCKER_USER --password-stdin
            make docker_tag
            make docker_push
            # notify microbadger to update
            # https://microbadger.com/images/monicahq/monicahq
            curl -X POST $MICROBADGER_WEBHOOK

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore: /l10n_master.*/
            tags:
              only: /.*/
      - tests-7.2:
          requires:
            - build
          filters:
            branches:
              ignore: /l10n_master.*/
            tags:
              only: /.*/
      - psalm:
          requires:
            - build
          filters:
            branches:
              ignore: /l10n_master.*/
            tags:
              only: /.*/
      - phpstan:
          requires:
            - build
          filters:
            branches:
              ignore: /l10n_master.*/
            tags:
              only: /.*/
      - tests-browser-7.2:
          requires:
            - build
          filters:
            branches:
              ignore: /l10n_master.*/
            tags:
              only: /.*/
      - reporting:
          requires:
            - tests-7.2
            - tests-browser-7.2
          filters:
            branches:
              ignore: /l10n_master.*/
            tags:
              only: /.*/
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
            tags:
              only: /^v\d+\.\d+(\.\d+)?(-\S*)?$/
      - deploy-assets:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
      - deploy-dist:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+(\.\d+)?(-\S*)?$/
      - deploy-docker-master:
          filters:
            branches:
              only:
                - master
      - deploy-docker-staging:
          requires:
            - deploy-docker-master
          filters:
            branches:
              only:
                - master
      - deploy-docker:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+(\.\d+)?(-\S*)?$/
