name: PHP linting (Pint)

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: Lint php ${{ github.ref }}
  cancel-in-progress: true


jobs:
  phplint:
    runs-on: ubuntu-latest
    name: PHP linting (Pint)

    strategy:
      fail-fast: false

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Get pint version
        id: pint
        run: |
          echo "version=$(composer show laravel/pint --locked --format=json | jq -r '.versions[0]' | sed 's/v//')" >> $GITHUB_OUTPUT

      - name: laravel-pint
        uses: aglipanci/laravel-pint-action@2.1.0
        with:
          configPath: pint.json
          pintVersion: ${{ steps.pint.outputs.version }}

      - name: Check if there is any file update needed
        run: |
          status=$(git status --porcelain)
          if [ -n "$status" ]; then
            echo -e "Waiting modifications:\n$status"
            echo "::error::Laravel pint found fixes. Please run 'vendor/bin/pint' prior to your next commit."
            exit -1
          fi
