name: Static analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  php-version: '8.2'

concurrency:
  group: Static ${{ github.ref }}
  cancel-in-progress: true

jobs:
  statics:
    uses: monicahq/workflows/.github/workflows/static.yml@init
    with:
      php-version: 8.2
